OFFLINE_ALARMS = {
    "BASE STATION FAULTY",
    "BCF FAULTY",
    "BN EMS Alarm NE Communication Failure",
    "BTS Down",
    "BTS O&M LINK FAILURE",
    "Communication FAIL",
    "Ericsson 2G NE Down",
    "Ericsson 4G NE Down",
    "Ericsson 4G S1 NE Down",
    "Heartbeat Failure",
    "Huawei 2G NE Down",
    "Huawei 4G NE Down",
    "Huawei 4G S1 NE Down",
    "Loss of communications with NE",
    "NE Is Disconnected",
    "NE O&M CONNECTION FAILURE",
    "NE OM CONNECTION FAILURE",
    "NE is Disconnected",
    "NE3SWS AGENT NOT RESPONDING TO REQUESTS",
    "NE_COMMU_BREAK",
    "NE_NOT_LOGIN",
    "NodeB Down",
    "Nokia 2G NE Down",
    "Nokia 4G NE Down",
    "Nokia 4G S1 NE Down",
    "ReachabilityProblem",
    "The Device is offline",
    "The link between the server and the NE is broken",
    "WCDMA BASE STATION OUT OF USE",
    "eNodeB Out of Service",
    "gNodeB Out of Service",
}

POWER_ALARMS = {
    "Device Powered Off",
    "Ethernet Physical (ETPI) Remote dying gasp event",
    "Low Input Voltage",
    "Mains Failure",
    "POWER_ABNORMAL",
    "POWER_ALM Power Invalid",
    "Power Fail(Entity)",
    "Power Supply",
    "RPU powered off",
    "The main power supply abnormal",
    "The voltage of the power supply is abnormal.",
    "cseShutDownNotify",
    "DC Low Voltage",
    "Genset Stop"
}

LINK_ALARMS = {
    "E1 LOS",
    "ETH LOS",
    "ETH_LINK_DOWN",
    "ETH_LOS",
    "Ethernet Physical (ETPI) Interface down",
    "Ethernet Physical (ETPI) LOS",
    "Ethernet Physical (ETPI) Port down",
    "Ethernet port disconnected",
    "IF_CABLE_OPEN",
    "InterfaceDown",
    "LINK_DOWN",
    "LOF",
    "Link Down",
    "Link Failure",
    "MW_LOF",
    "Microwave link critical alarm.",
    "Physical Port Down",
    "S1AP Link Down",
    "Transmission unit link break",
}

CRITICAL_ALARMS = OFFLINE_ALARMS | POWER_ALARMS | LINK_ALARMS
