#!/usr/bin/env python3
"""Infer BRUNCH fault groups using a trained alarm-flow BRUNCH artifact."""

from __future__ import annotations

from dataclasses import replace
import json
import os
from argparse import ArgumentParser

if __package__ in (None, ""):
    from _script_env import ensure_repo_root

    ensure_repo_root(1)

from alarm_flow_brunch.aggregator import infer_alarm_flow, load_alarm_brunch_artifact
from alarm_flow_brunch.region_filter import parse_regions
from alarm_flow_brunch.visual_output import write_visual_groups
from alarm_flow_isahp.alarm_io import load_ordered_alarm_events
from topology_resources import NE_GRAPH_JSON, SITE_GRAPH_BY_NE_JSON, SITE_GRAPH_JSON, resource_display


def _write_json(path, payload):
    with open(path, "w", encoding="utf-8") as stream:
        json.dump(payload, stream, ensure_ascii=False, indent=2)
        stream.write("\n")


def _write_jsonl(path, records):
    count = 0
    with open(path, "w", encoding="utf-8") as stream:
        for record in records:
            stream.write(json.dumps(record, ensure_ascii=False) + "\n")
            count += 1
    return count


def main():
    parser = ArgumentParser(description="Infer alarm-flow BRUNCH fault groups from a trained artifact.")
    parser.add_argument("model", help="Model artifact generated by train_alarm_brunch.py.")
    parser.add_argument("alarms", help="Raw alarms or prepare_sorted_alarms cache consumed by match_rules.")
    parser.add_argument("-o", "--output", required=True, help="Output fault group JSON.")
    parser.add_argument("--edges-output", default="", help="Optional branching edge JSONL.")
    parser.add_argument(
        "--visual-output",
        default="",
        help="Optional visualization JSONL compatible with the fault group browser and propagation visualizer.",
    )
    parser.add_argument(
        "--topo",
        default=SITE_GRAPH_BY_NE_JSON,
        help=f"Site topology for raw alarm inputs. Default: {resource_display('site_graph_by_ne.json')}.",
    )
    parser.add_argument(
        "--ne-graph",
        default=NE_GRAPH_JSON,
        help=f"NE graph for raw alarm inputs. Default: {resource_display('ne_graph.json')}.",
    )
    parser.add_argument(
        "--site-graph",
        default=SITE_GRAPH_JSON,
        help=f"Site metadata for --visual-output. Default: {resource_display('site_graph.json')}.",
    )
    parser.add_argument(
        "--visual-ne-scope",
        choices=("alarm-only", "site-context"),
        default="alarm-only",
        help="NEs in --visual-output: grouped alarm devices only, or all devices at group sites.",
    )
    parser.add_argument("--start-time", default="", help="Raw-input first occurrence lower bound.")
    parser.add_argument("--end-time", default="", help="Raw-input first occurrence upper bound.")
    parser.add_argument("--clear-delay-sec", type=float, default=0.0, help="Raw-input clear delay.")
    parser.add_argument("--n-sweeps", type=int, default=10, help="BRUNCH sweeps for branching inference.")
    parser.add_argument("--burn-in", type=int, default=0, help="Inference burn-in. Default: 0.")
    parser.add_argument("--refit-params", action="store_true", help="Continue refitting edge influence on this input.")
    parser.add_argument("--no-warm-start", action="store_true", help="Disable nearest-in-window warm start.")
    parser.add_argument("--min-group-events", type=int, default=1, help="Drop groups smaller than this.")
    parser.add_argument(
        "--parent-selection",
        choices=("sample", "argmax"),
        default=None,
        help=(
            "Override artifact parent selection. sample keeps stochastic inference; "
            "argmax uses deterministic maximum-weight parents."
        ),
    )
    parser.add_argument(
        "--regions",
        "--region",
        dest="regions",
        action="append",
        default=None,
        help=(
            "Override artifact regions. Repeat this option or pass comma-separated values; "
            "omit to reuse the model's regions."
        ),
    )
    parser.add_argument("--seed", type=int, default=0, help="Random seed.")
    args = parser.parse_args()

    artifact = load_alarm_brunch_artifact(args.model)
    regions = parse_regions(args.regions) if args.regions is not None else artifact.config.regions
    parent_selection = args.parent_selection or artifact.config.parent_selection
    infer_config = replace(
        artifact.config,
        n_sweeps=args.n_sweeps,
        burn_in=args.burn_in,
        refit_params=args.refit_params,
        warm_start=not args.no_warm_start,
        min_group_events=args.min_group_events,
        regions=regions,
        parent_selection=parent_selection,
        seed=args.seed,
    )
    alarm_events, alarm_metadata = load_ordered_alarm_events(
        args.alarms,
        topo_path=args.topo,
        ne_graph_path=args.ne_graph,
        start_time=args.start_time or None,
        end_time=args.end_time or None,
        clear_delay_sec=args.clear_delay_sec,
        regions=infer_config.regions,
    )
    output = infer_alarm_flow(
        alarm_events,
        artifact,
        config=infer_config,
        region_filter_stats=(alarm_metadata or {}).get("region_filter"),
    )
    payload = output.to_json_payload()
    payload["metadata"]["input"] = os.path.abspath(args.alarms)
    payload["metadata"]["model"] = os.path.abspath(args.model)
    payload["metadata"]["alarm_metadata"] = alarm_metadata
    _write_json(args.output, payload)
    print(
        f"BRUNCH fault groups written to: {args.output}; "
        f"groups={output.metadata['group_count']}, "
        f"events={output.metadata['modeled_event_count']}, "
        f"types={output.metadata['type_count']}, "
        f"active_edges={output.metadata['active_edge_count']}"
    )
    if args.edges_output:
        edge_count = _write_jsonl(args.edges_output, output.edges)
        print(f"branching edges written to: {args.edges_output}; edges={edge_count}")
    if args.visual_output:
        visual_count = write_visual_groups(
            args.visual_output,
            output.groups,
            ne_graph_path=args.ne_graph,
            site_graph_path=args.site_graph,
            ne_scope=args.visual_ne_scope,
        )
        print(f"visual groups written to: {args.visual_output}; groups={visual_count}")


if __name__ == "__main__":
    main()
