#!/usr/bin/env python3
"""Export ISAHP instance-level causal edges for an ordered alarm stream."""

import json
import os
from argparse import ArgumentParser

if __package__ in (None, ""):
    from _script_env import ensure_repo_root

    ensure_repo_root(1)

from alarm_flow_isahp.alarm_io import load_ordered_alarm_events
from alarm_flow_isahp.model import (
    AlarmTargetWindowDataset,
    average_type_score_matrix,
    collate_alarm_target_windows,
    iter_instance_edges,
    load_alarm_isahp_artifact,
    require_torch,
)
from alarm_flow_isahp.ne_topology import NETopologyIndex
from alarm_flow_isahp.sequences import (
    AlarmSequenceConfig,
    AlarmVocabs,
    build_alarm_sequences,
)
from topology_resources import NE_GRAPH_JSON, SITE_GRAPH_BY_NE_JSON, resource_display


def _write_json(path, payload):
    with open(path, "w", encoding="utf-8") as stream:
        json.dump(payload, stream, ensure_ascii=False, indent=2)
        stream.write("\n")


def _write_jsonl(path, records):
    count = 0
    with open(path, "w", encoding="utf-8") as stream:
        for record in records:
            stream.write(json.dumps(record, ensure_ascii=False) + "\n")
            count += 1
    return count


def _type_score_payload(labels, scores, counts):
    return {
        "matrix_axes": {
            "rows": "target_alarm_type",
            "columns": "historical_source_alarm_type",
        },
        "labels": list(labels),
        "scores": scores.tolist(),
        "counts": counts.tolist(),
    }


def main():
    parser = ArgumentParser(description="Infer alarm ISAHP instance-level causal edges.")
    parser.add_argument("model", help="Model artifact generated by train_alarm_isahp.py.")
    parser.add_argument("alarms", help="Raw alarms or prepare_sorted_alarms cache consumed by match_rules.")
    parser.add_argument("-o", "--output", required=True, help="Output instance edge JSONL.")
    parser.add_argument("--type-score-output", default="", help="Optional type-level causal score JSON.")
    parser.add_argument(
        "--topo",
        default=SITE_GRAPH_BY_NE_JSON,
        help=f"Site topology for raw alarm inputs. Default: {resource_display('site_graph_by_ne.json')}.",
    )
    parser.add_argument(
        "--ne-graph",
        default=NE_GRAPH_JSON,
        help=f"NE graph for raw alarm inputs. Default: {resource_display('ne_graph.json')}.",
    )
    parser.add_argument("--start-time", default="", help="Raw-input first occurrence lower bound.")
    parser.add_argument("--end-time", default="", help="Raw-input first occurrence upper bound.")
    parser.add_argument("--clear-delay-sec", type=float, default=0.0, help="Raw-input clear delay.")
    parser.add_argument(
        "--topology-max-hops",
        type=int,
        default=2,
        help="Maximum NE graph hops encoded as soft pair features. Default: 2.",
    )
    parser.add_argument(
        "--top-parents",
        type=int,
        default=5,
        help="Historical parents exported per target event. <=0 exports every valid parent.",
    )
    parser.add_argument("--batch-size", type=int, default=16, help="Target-window batch size for type-level matrix.")
    parser.add_argument("--device", default="auto", help="PyTorch device, for example auto, cpu, cuda.")
    args = parser.parse_args()

    require_torch()
    import torch

    device_name = args.device
    if device_name == "auto":
        device_name = "cuda" if torch.cuda.is_available() else "cpu"
    device = torch.device(device_name)
    model, artifact = load_alarm_isahp_artifact(args.model, map_location=device)
    model = model.to(device)
    vocabs = AlarmVocabs.from_dict(artifact["vocabs"])
    sequence_config = AlarmSequenceConfig.from_dict(artifact["sequence_config"])

    alarm_events, alarm_metadata = load_ordered_alarm_events(
        args.alarms,
        topo_path=args.topo,
        ne_graph_path=args.ne_graph,
        start_time=args.start_time or None,
        end_time=args.end_time or None,
        clear_delay_sec=args.clear_delay_sec,
    )
    topology_index = NETopologyIndex.from_file(args.ne_graph, max_hops=args.topology_max_hops)
    sequences, sequence_stats = build_alarm_sequences(
        alarm_events,
        vocabs,
        sequence_config,
        topology_index=topology_index,
    )
    if not sequences:
        raise ValueError("no global alarm flow matches the model vocabulary and preprocessing config")
    edge_count = _write_jsonl(
        args.output,
        iter_instance_edges(model, sequences, device, top_parents=args.top_parents),
    )
    print(
        f"instance edges written to: {args.output}; edges={edge_count}, "
        f"target_windows={sequence_stats['target_window_count']}, device={device}"
    )
    if sequence_stats.get("dropped_event_count"):
        print(f"events not covered by trained vocab or sequence windows: {sequence_stats['dropped_event_count']}")

    if args.type_score_output:
        dataloader = torch.utils.data.DataLoader(
            AlarmTargetWindowDataset(sequences),
            batch_size=args.batch_size,
            shuffle=False,
            collate_fn=collate_alarm_target_windows,
        )
        type_scores, type_counts = average_type_score_matrix(model, dataloader, device)
        payload = _type_score_payload(vocabs.type_vocab.labels, type_scores, type_counts)
        payload["inference"] = {
            "input": os.path.abspath(args.alarms),
            "alarm_metadata": alarm_metadata,
            "sequence_stats": sequence_stats,
        }
        _write_json(args.type_score_output, payload)
        print(f"type causal score matrix written to: {args.type_score_output}")


if __name__ == "__main__":
    main()
